# Generated by Django 3.1.3 on 2022-09-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bo_no', models.AutoField(primary_key=True, serialize=False)),
                ('bo_title', models.CharField(max_length=100)),
                ('bo_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('bo_hit', models.IntegerField(blank=True, default=0, null=True)),
                ('bo_content', models.CharField(max_length=1000)),
                ('bo_img', models.FileField(blank=True, upload_to='community/')),
                ('groupno', models.IntegerField(default=0)),
                ('orderno', models.IntegerField(default=0)),
                ('u_no', models.ForeignKey(db_column='u_no', on_delete=django.db.models.deletion.DO_NOTHING, to='Members.user')),
            ],
            options={
                'db_table': 'board',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('co_no', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.user')),
            ],
            options={
                'verbose_name': '답글',
                'verbose_name_plural': '답글',
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
