# Generated by Django 3.1.3 on 2022-09-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0001_initial'),
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qcategory',
            fields=[
                ('qcate_no', models.AutoField(primary_key=True, serialize=False)),
                ('qcate_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'qcategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qna_no', models.AutoField(primary_key=True, serialize=False)),
                ('qna_title', models.CharField(max_length=100)),
                ('qna_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('qna_content', models.CharField(max_length=1000)),
                ('qna_img', models.CharField(blank=True, max_length=300, null=True)),
                ('groupno', models.IntegerField(default=0)),
                ('orderno', models.IntegerField(default=0)),
                ('b_no', models.ForeignKey(db_column='b_no', on_delete=django.db.models.deletion.DO_NOTHING, to='Brands.brand')),
                ('qcate_no', models.ForeignKey(db_column='qcate_no', on_delete=django.db.models.deletion.DO_NOTHING, to='CS.qcategory')),
                ('u_no', models.ForeignKey(db_column='u_no', on_delete=django.db.models.deletion.DO_NOTHING, to='Members.user')),
            ],
            options={
                'db_table': 'qna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_no', models.AutoField(primary_key=True, serialize=False)),
                ('faq_title', models.CharField(max_length=100)),
                ('faq_reply', models.CharField(max_length=1000)),
                ('qcate_no', models.ForeignKey(db_column='qcate_no', on_delete=django.db.models.deletion.DO_NOTHING, to='CS.qcategory')),
            ],
            options={
                'db_table': 'faq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CS_Comment',
            fields=[
                ('cs_co_no', models.AutoField(primary_key=True, serialize=False)),
                ('cs_content', models.TextField()),
                ('cs_logtime', models.DateTimeField(auto_now_add=True)),
                ('cs_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS.qna')),
                ('cs_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Brands.brand')),
                ('cs_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.user')),
            ],
            options={
                'verbose_name': '고객센터 답글',
                'verbose_name_plural': '고객센터 답글',
                'db_table': 'cs_comment',
                'managed': True,
            },
        ),
    ]
