# Generated by Django 3.1.3 on 2022-09-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('g_no', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=20)),
                ('g_discount', models.CharField(max_length=20)),
                ('g_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_no', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=20, unique=True)),
                ('u_pw', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=20)),
                ('u_nickname', models.CharField(max_length=20)),
                ('u_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('u_email', models.CharField(blank=True, max_length=50, null=True)),
                ('u_birth', models.DateField(blank=True, null=True)),
                ('u_joindate', models.DateTimeField(blank=True, null=True)),
                ('u_self_cert', models.IntegerField(blank=True, default=0, null=True)),
                ('u_refundnum', models.CharField(blank=True, max_length=20, null=True)),
                ('u_point', models.IntegerField(blank=True, default=0, null=True)),
                ('u_dep', models.IntegerField(blank=True, default=0, null=True)),
                ('g_no', models.ForeignKey(blank=True, db_column='g_no', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.grade')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_cardnum', models.CharField(max_length=20)),
                ('u_no', models.ForeignKey(db_column='u_no', on_delete=django.db.models.deletion.CASCADE, to='Members.user')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('d_no', models.AutoField(primary_key=True, serialize=False)),
                ('d_addr', models.CharField(max_length=50)),
                ('d_recipient', models.CharField(max_length=20)),
                ('d_name', models.CharField(max_length=20)),
                ('d_phone', models.CharField(max_length=20)),
                ('d_option', models.CharField(blank=True, default='없음', max_length=100, null=True)),
                ('u_no', models.ForeignKey(db_column='u_no', on_delete=django.db.models.deletion.CASCADE, to='Members.user')),
            ],
            options={
                'db_table': 'delivery',
                'managed': True,
            },
        ),
    ]
