# Generated by Django 3.1.3 on 2022-09-19 10:06

import Brands.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bigcate',
            fields=[
                ('bigcate_no', models.AutoField(primary_key=True, serialize=False)),
                ('bigcate_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bigcate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_url', models.CharField(max_length=100)),
                ('b_addr', models.CharField(max_length=30)),
                ('b_managername', models.CharField(max_length=20)),
                ('b_korname', models.CharField(max_length=20)),
                ('b_engname', models.CharField(max_length=20)),
                ('b_info', models.TextField()),
                ('b_img', models.FileField(null=True, upload_to='brands_img/')),
                ('b_id', models.CharField(max_length=20)),
                ('b_pw', models.CharField(max_length=20)),
                ('b_hp', models.CharField(max_length=20)),
                ('b_email', models.CharField(max_length=20)),
                ('b_serialnum', models.CharField(max_length=20)),
                ('b_joindate', models.DateTimeField(auto_now_add=True, null=True)),
                ('b_refund_num', models.CharField(blank=True, default='등록필요', max_length=20, null=True)),
                ('b_likecnt', models.IntegerField(blank=True, default=0, null=True)),
                ('b_dep', models.IntegerField(blank=True, default=1, null=True)),
                ('b_confirm', models.IntegerField(blank=True, default=2, null=True)),
                ('b_sellmoney', models.IntegerField(blank=True, default=0, null=True)),
                ('b_hit', models.IntegerField(blank=True, default=0, null=True)),
                ('b_sellcnt', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brandcate',
            fields=[
                ('bc_no', models.AutoField(primary_key=True, serialize=False)),
                ('bc_catename', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'brandcate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('col_no', models.AutoField(primary_key=True, serialize=False)),
                ('col_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('it_no', models.AutoField(primary_key=True, serialize=False)),
                ('it_name', models.CharField(max_length=20)),
                ('it_info', models.CharField(max_length=300)),
                ('it_price', models.IntegerField()),
                ('it_point', models.IntegerField()),
                ('it_discount', models.IntegerField()),
                ('it_regdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('it_likecnt', models.IntegerField(blank=True, default=0, null=True)),
                ('b_no', models.ForeignKey(db_column='b_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.brand')),
                ('bigcate_no', models.ForeignKey(db_column='bigcate_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.bigcate')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shoesize',
            fields=[
                ('ss_no', models.AutoField(primary_key=True, serialize=False)),
                ('ss_name', models.CharField(max_length=20)),
                ('bigcate_no', models.ForeignKey(db_column='bigcate_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.bigcate')),
                ('it_no', models.ForeignKey(db_column='it_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.item')),
            ],
            options={
                'db_table': 'shoesize',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('bigcate_no', models.ForeignKey(db_column='bigcate_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.bigcate')),
                ('it_no', models.ForeignKey(db_column='it_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.item')),
            ],
            options={
                'db_table': 'size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('st_no', models.AutoField(primary_key=True, serialize=False)),
                ('st_cnt', models.IntegerField()),
                ('st_sellcnt', models.IntegerField()),
                ('st_status', models.CharField(blank=True, max_length=20, null=True)),
                ('b_no', models.ForeignKey(db_column='b_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.brand')),
                ('col_no', models.ForeignKey(db_column='col_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.color')),
                ('it_no', models.ForeignKey(db_column='it_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.item')),
                ('s_no', models.ForeignKey(blank=True, db_column='s_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='Brands.size')),
                ('ss_no', models.ForeignKey(blank=True, db_column='ss_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='Brands.shoesize')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('opt_no', models.AutoField(primary_key=True, serialize=False)),
                ('opt_name', models.CharField(max_length=20)),
                ('it_no', models.ForeignKey(db_column='it_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.item')),
            ],
            options={
                'db_table': 'options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Midcate',
            fields=[
                ('midcate_no', models.AutoField(primary_key=True, serialize=False)),
                ('midcate_name', models.CharField(max_length=20)),
                ('bigcate_no', models.ForeignKey(db_column='bigcate_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.bigcate')),
            ],
            options={
                'db_table': 'midcate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemimage',
            fields=[
                ('ii_no', models.AutoField(primary_key=True, serialize=False)),
                ('ii_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ii_img', models.FileField(null=True, upload_to=Brands.models.id_dir_path)),
                ('it_no', models.ForeignKey(db_column='it_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.item')),
            ],
            options={
                'db_table': 'itemimage',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='midcate_no',
            field=models.ForeignKey(db_column='midcate_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.midcate'),
        ),
        migrations.AddField(
            model_name='color',
            name='it_no',
            field=models.ForeignKey(db_column='it_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.item'),
        ),
        migrations.AddField(
            model_name='brand',
            name='bc_no',
            field=models.ForeignKey(db_column='bc_no', on_delete=django.db.models.deletion.CASCADE, to='Brands.brandcate'),
        ),
    ]
