# Generated by Django 3.1.3 on 2022-09-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0001_initial'),
        ('Menubar', '0001_initial'),
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('m_no', models.AutoField(primary_key=True, serialize=False)),
                ('m_size', models.IntegerField()),
                ('m_color', models.IntegerField()),
                ('m_puton', models.IntegerField()),
                ('m_rebuy', models.IntegerField()),
                ('m_tot', models.DecimalField(decimal_places=2, max_digits=3)),
                ('m_logtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('m_content', models.CharField(max_length=1000)),
                ('m_title', models.CharField(max_length=100)),
                ('m_img', models.CharField(blank=True, max_length=300, null=True)),
                ('groupno', models.IntegerField(default=0)),
                ('orderno', models.IntegerField(default=0)),
                ('b_no', models.ForeignKey(db_column='b_no', on_delete=django.db.models.deletion.DO_NOTHING, to='Brands.brand')),
                ('buy_no', models.ForeignKey(db_column='buy_no', on_delete=django.db.models.deletion.DO_NOTHING, to='Menubar.buy')),
                ('u_no', models.ForeignKey(db_column='u_no', on_delete=django.db.models.deletion.DO_NOTHING, to='Members.user')),
            ],
            options={
                'db_table': 'mark',
                'managed': True,
            },
        ),
    ]
